import streamlit as st
import pandas as pd
import pickle
import os
from utils.data_fetcher import fetch_recent_news
from utils.ai_advisor import generate_news_summary

def render_news():
    st.markdown("<h1>News & Sentiment Tracker</h1>", unsafe_allow_html=True)
    st.markdown("<p>Real-time news for your holdings, analyzed by our custom Natural Language Processing model.</p>", unsafe_allow_html=True)
    
    # ML TRANSPARENCY SECTION
    with st.expander("About the Machine Learning Model (Transparency)"):
        st.markdown("""
        **Model Overview:**
        The sentiment score below is generated by an **NLP Logistic Regression Classifier** and a **TF-IDF Vectorizer** trained entirely offline.
        
        **Data Source:**
        The model was trained on the Kaggle "**Tweet Sentiment's Impact on Stock Returns**" dataset. 
        It learned the linguistic patterns of nearly 6,000 financial tweets and their impact on stock performance.
        
        **Performance Metrics:**
        - **Accuracy:** 80.07%
        - **F1-Score (Positive Sentiment):** 84%
        - **F1-Score (Negative Sentiment):** 74%
        - **Target:** Predict if a headline is Positive (+1), Neutral (0), or Negative (-1) for the associated stock.
        """)
        
    holdings = st.session_state.holdings
    
    if not holdings:
        st.warning("No holdings found.")
        return
        
    tickers = list(holdings.keys())
    
    # Load ML Models
    vec_path = "ml_pipeline/tfidf_vectorizer.pkl"
    model_path = "ml_pipeline/sentiment_model.pkl"
    
    clf = None
    vectorizer = None
    
    if os.path.exists(vec_path) and os.path.exists(model_path):
        with open(vec_path, 'rb') as f:
            vectorizer = pickle.load(f)
        with open(model_path, 'rb') as f:
            clf = pickle.load(f)
    else:
        st.warning("Sentiment ML Models not found. Headlines will be fetched but not scored.")
        
    st.markdown("### Recent Portfolio Headlines")
    
    all_news = []
    
    with st.spinner("Fetching news..."):
        for ticker in tickers: # Fetch news for all holdings
            news_items = fetch_recent_news([ticker], limit=3)[ticker] # Limit to 3 articles per asset to prevent spam
            for item in news_items:
                all_news.append({
                    'Ticker': ticker,
                    'Title': item['title'],
                    'Publisher': item['publisher'],
                    'Link': item['link']
                })
                
    if not all_news:
        st.info("No recent news found for your top holdings.")
        return
        
    df_news = pd.DataFrame(all_news)
    
    # Apply ML Scoring if models loaded
    if clf and vectorizer:
        with st.spinner("Scoring news with NLP model..."):
            # Clean/Vectorize
            text_features = vectorizer.transform(df_news['Title'])
            # Predict (-1, 0, 1)
            predictions = clf.predict(text_features)
            df_news['ML Sentiment'] = predictions
            
            # Map number to readable tag
            sentiment_map = {1: "🟢 Positive", 0: "⚪ Neutral", -1: "🔴 Negative"}
            df_news['Sentiment Label'] = df_news['ML Sentiment'].map(sentiment_map)
    else:
        df_news['Sentiment Label'] = "N/A"
        
    # Aggregate sentiment by ticker
    if 'ML Sentiment' in df_news.columns:
        agg_sentiment = df_news.groupby('Ticker')['ML Sentiment'].mean().reset_index()
        st.markdown("#### Average Sentiment by Asset")
        
        cols = st.columns(len(agg_sentiment))
        for idx, row in agg_sentiment.iterrows():
            with cols[idx]:
                score = row['ML Sentiment']
                st.metric(row['Ticker'], f"{score:+.2f}", help="Range -1.0 (Very Negative) to +1.0 (Very Positive)")
                
    st.markdown("<div class='divider'></div>", unsafe_allow_html=True)
    
    # Display News List
    col1, col2 = st.columns([2, 1])
    
    with col1:
        st.dataframe(
            df_news[['Ticker', 'Sentiment Label', 'Title', 'Publisher', 'Link']],
            column_config={
                "Link": st.column_config.LinkColumn("Article Link")
            },
            use_container_width=True,
            hide_index=True,
            height=400
        )
        
    with col2:
        st.markdown("#### The AI Synthesis")
        if st.button("Synthesize The Above with Claude"):
            with st.spinner("Claude is reading the headlines..."):
                summary = generate_news_summary(
                    news_items=all_news[:10], # Send top 10 to avoid token limits
                    holdings=tickers,
                    eli10_mode=st.session_state.get('eli10_mode', False)
                )
                st.info(summary)
        else:
            st.markdown("<p style='color:#1E1E1E; font-size:0.9rem;'>Click to summarize the fundamental impact of these articles.</p>", unsafe_allow_html=True)
