import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import joblib
import os
from utils.data_fetcher import fetch_recent_news
from utils.ai_advisor import generate_news_summary

def render_news():
    st.markdown("<h1>News & Sentiment Tracker</h1>", unsafe_allow_html=True)
    st.markdown("<p>Real-time news for your holdings, analyzed by our custom Natural Language Processing model.</p>", unsafe_allow_html=True)
    
    # ML TRANSPARENCY SECTION
    with st.expander("About the Machine Learning Model (Transparency)"):
        st.markdown("""
        **Model Overview:**
        The sentiment score is generated by a **Logistic Regression + TF-IDF pipeline** trained offline and selected via `GridSearchCV`
        over C, max_features, and n-gram range.

        **Data Source:**
        Trained on the Kaggle "**Tweet Sentiment's Impact on Stock Returns**" dataset (~6,000 financial tweets)
        using a **sequential (time-ordered) split** to prevent temporal data leakage.

        **Target:** Predict if a headline is Positive (+1) or Negative (-1) for the associated stock.
        A continuous sentiment score (range -1 to +1) is derived from `predict_proba` for finer granularity.
        Portfolio-weighted sentiment is computed and fed into cross-component LLM prompts.

        **Note:** See the **ML Transparency** tab for full evaluation metrics (classification report, ROC curve, confusion matrix, top words, cross-validation).
        """)
        
    holdings = st.session_state.holdings
    
    if not holdings:
        st.warning("No holdings found.")
        return
        
    tickers = list(holdings.keys())
    
    # Load ML Pipeline
    pipeline_path = "ml_pipeline/sentiment_pipeline.joblib"
    
    pipeline = None
    
    if os.path.exists(pipeline_path):
        pipeline = joblib.load(pipeline_path)
    else:
        st.warning("Sentiment ML Models not found. Headlines will be fetched but not scored.")
        
    st.markdown("### Recent Portfolio Headlines")
    
    all_news = []
    
    with st.spinner("Fetching news..."):
        for ticker in tickers: # Fetch news for all holdings
            news_items = fetch_recent_news([ticker], limit=3)[ticker] # Limit to 3 articles per asset to prevent spam
            for item in news_items:
                all_news.append({
                    'Ticker': ticker,
                    'Title': item['title'],
                    'Publisher': item['publisher'],
                    'Link': item['link']
                })
                
    if not all_news:
        st.info("No recent news found for your top holdings.")
        return
        
    df_news = pd.DataFrame(all_news)
    
    # Apply ML Scoring if model loaded
    if pipeline:
        with st.spinner("Scoring news with NLP model..."):
            # Use predict_proba for a continuous sentiment score instead of
            # the hard binary prediction.  The model has classes [-1, 1].
            probas = pipeline.predict_proba(df_news['Title'])
            # Continuous score: P(positive) - P(negative), range [-1, +1]
            pos_idx = list(pipeline.classes_).index(1)
            neg_idx = list(pipeline.classes_).index(-1)
            df_news['ML Sentiment'] = probas[:, pos_idx] - probas[:, neg_idx]

            # Map to label using confidence thresholds
            def _label(score):
                if score > 0.15:
                    return "🟢 Positive"
                elif score < -0.15:
                    return "🔴 Negative"
                return "⚪ Neutral"

            df_news['Sentiment Label'] = df_news['ML Sentiment'].apply(_label)
    else:
        df_news['Sentiment Label'] = "N/A"
        
    # Aggregate sentiment by ticker
    if 'ML Sentiment' in df_news.columns:
        agg_sentiment = df_news.groupby('Ticker')['ML Sentiment'].mean().reset_index()
        agg_sentiment = agg_sentiment.sort_values('ML Sentiment', ascending=True)

        # Compute portfolio-weighted sentiment and store for cross-view use
        from utils.data_fetcher import fetch_current_prices as _fcp
        _prices = _fcp(tickers)
        _total_val = sum(holdings[t] * _prices.get(t, 0) for t in tickers)
        _weights = {t: (holdings[t] * _prices.get(t, 0)) / _total_val if _total_val > 0 else 0 for t in tickers}
        _sent_by_ticker = dict(zip(agg_sentiment['Ticker'], agg_sentiment['ML Sentiment']))
        portfolio_sentiment = sum(
            _sent_by_ticker.get(t, 0) * _weights.get(t, 0) for t in tickers
        )
        worst_t = agg_sentiment.iloc[0]
        best_t = agg_sentiment.iloc[-1]
        st.session_state['portfolio_sentiment'] = {
            'score': round(float(portfolio_sentiment), 3),
            'worst_ticker': worst_t['Ticker'],
            'worst_score': round(float(worst_t['ML Sentiment']), 3),
            'best_ticker': best_t['Ticker'],
            'best_score': round(float(best_t['ML Sentiment']), 3),
            'per_ticker': {row['Ticker']: round(float(row['ML Sentiment']), 3) for _, row in agg_sentiment.iterrows()},
        }

        st.markdown("#### Average Sentiment by Asset")

        fig_sent = go.Figure()
        fig_sent.add_trace(go.Bar(
            y=agg_sentiment['Ticker'],
            x=agg_sentiment['ML Sentiment'],
            orientation='h',
            marker_color=[
                '#C44536' if s < -0.2 else ('#1F8A70' if s > 0.2 else '#3A6EA5')
                for s in agg_sentiment['ML Sentiment']
            ],
            text=[f"{s:+.2f}" for s in agg_sentiment['ML Sentiment']],
            textposition='outside',
        ))
        fig_sent.update_layout(
            xaxis_title='Sentiment Score',
            xaxis_range=[-1.1, 1.1],
            yaxis_title='',
            margin=dict(t=10, b=40, l=80, r=40),
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)',
            height=max(250, len(agg_sentiment) * 40),
        )
        fig_sent.add_vline(x=0, line_dash="dash", line_color="#999")
        st.plotly_chart(fig_sent, use_container_width=True)
                
    st.markdown("<div class='divider'></div>", unsafe_allow_html=True)
    
    # Display News List
    col_title, col_btn = st.columns([3, 1])
    with col_title:
        st.markdown("#### Portfolio Headlines")
    with col_btn:
        synthesize_clicked = st.button("Synthesize with Claude", use_container_width=True)

    st.dataframe(
        df_news[['Ticker', 'Sentiment Label', 'Title', 'Publisher', 'Link']],
        column_config={
            "Link": st.column_config.LinkColumn("Article Link")
        },
        use_container_width=True,
        hide_index=True,
        height=400
    )

    if synthesize_clicked:
        with st.spinner("Claude is reading the headlines..."):
            summary = generate_news_summary(
                news_items=all_news[:10],
                holdings=tickers,
                eli10_mode=st.session_state.get('eli10_mode', False)
            )
        st.markdown("#### AI Synthesis")
        st.info(summary)
